import type { SharedProject } from "./shared-portfolio.ts";
export type GitHubRepoCollaboration = { repositoryId: string; projectName: string; defaultBranch: string | null; pushedAt: string | null; archived: boolean | null; openPrs: number | null; mergedToday: number | null; reviewRequests: number | null; ci: "success" | "failure" | "pending" | "unknown"; ciAt: string | null; status: "ready" | "unavailable" };
export type GitHubCollaboration = { status: "ready" | "partial" | "unavailable" | "disabled"; fetchedAt: string; authenticated: boolean; repos: GitHubRepoCollaboration[]; message: string };
type Fetcher = (input: string | URL | Request, init?: RequestInit) => Promise<Response>;
const cache = new Map<string, { expires: number; value: GitHubRepoCollaboration }>();
function repoSlug(repositoryId: string) { const parts = repositoryId.split("/"); return parts[0] === "github.com" && parts.length >= 3 ? `${parts[1]}/${parts.slice(2).join("/")}` : null; }
async function json(fetcher: Fetcher, url: string, headers: HeadersInit) { const response = await fetcher(url, { headers, signal: AbortSignal.timeout(4500) }); if (!response.ok) throw new Error(`GitHub HTTP ${response.status}`); return response.json(); }
async function loadOne(repositoryId: string, projectName: string, fetcher: Fetcher, token: string | undefined, now: number): Promise<GitHubRepoCollaboration> {
  const cached = cache.get(repositoryId); if (cached && cached.expires > now) return cached.value; const slug = repoSlug(repositoryId); if (!slug) return { repositoryId, projectName, defaultBranch: null, pushedAt: null, archived: null, openPrs: null, mergedToday: null, reviewRequests: null, ci: "unknown", ciAt: null, status: "unavailable" };
  const headers: Record<string, string> = { Accept: "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "CyberDJS-Nexus" }; if (token) headers.Authorization = `Bearer ${token}`;
  try { const base = `https://api.github.com/repos/${slug}`; const [repo, pulls, runs] = await Promise.all([json(fetcher, base, headers), json(fetcher, `${base}/pulls?state=all&sort=updated&direction=desc&per_page=30`, headers), json(fetcher, `${base}/actions/runs?per_page=1`, headers)]); const today = new Date(now).toISOString().slice(0, 10); const pullList = Array.isArray(pulls) ? pulls : []; const open = pullList.filter((pr) => pr?.state === "open"); const latest = Array.isArray(runs?.workflow_runs) ? runs.workflow_runs[0] : null; const conclusion = latest?.conclusion; const runStatus = latest?.status; const ci: GitHubRepoCollaboration["ci"] = conclusion === "success" ? "success" : conclusion && conclusion !== "neutral" && conclusion !== "skipped" ? "failure" : runStatus && runStatus !== "completed" ? "pending" : "unknown"; const value = { repositoryId, projectName, defaultBranch: typeof repo?.default_branch === "string" ? repo.default_branch : null, pushedAt: typeof repo?.pushed_at === "string" ? repo.pushed_at : null, archived: typeof repo?.archived === "boolean" ? repo.archived : null, openPrs: open.length, mergedToday: pullList.filter((pr) => typeof pr?.merged_at === "string" && pr.merged_at.slice(0, 10) === today).length, reviewRequests: open.reduce((sum, pr) => sum + (Array.isArray(pr?.requested_reviewers) ? pr.requested_reviewers.length : 0) + (Array.isArray(pr?.requested_teams) ? pr.requested_teams.length : 0), 0), ci, ciAt: typeof latest?.updated_at === "string" ? latest.updated_at : null, status: "ready" as const }; cache.set(repositoryId, { expires: now + 10 * 60000, value }); return value; } catch { const value = { repositoryId, projectName, defaultBranch: null, pushedAt: null, archived: null, openPrs: null, mergedToday: null, reviewRequests: null, ci: "unknown" as const, ciAt: null, status: "unavailable" as const }; cache.set(repositoryId, { expires: now + 2 * 60000, value }); return value; }
}
export async function loadGitHubCollaboration(projects: SharedProject[], options: { fetcher?: Fetcher; maxRepos?: number; now?: number; disabled?: boolean } = {}): Promise<GitHubCollaboration> {
  const now = options.now ?? Date.now(); const token = process.env.PCC_GITHUB_TOKEN ?? process.env.GITHUB_TOKEN; if (options.disabled ?? process.env.PCC_GITHUB_DISABLED === "1") return { status: "disabled", fetchedAt: new Date(now).toISOString(), authenticated: Boolean(token), repos: [], message: "GitHub live metadata disabled by PCC_GITHUB_DISABLED" };
  const candidates = projects.filter((p) => p.repositoryId?.startsWith("github.com/")).sort((a, b) => Number(b.isShared) - Number(a.isShared) || Number(b.repositoryNamespace === "cyberdjs") - Number(a.repositoryNamespace === "cyberdjs") || a.name.localeCompare(b.name)).slice(0, options.maxRepos ?? 10);
  if (!candidates.length) return { status: "unavailable", fetchedAt: new Date(now).toISOString(), authenticated: Boolean(token), repos: [], message: "No GitHub repositories in current portfolio" };
  const fetcher = options.fetcher ?? fetch; const repos: GitHubRepoCollaboration[] = []; for (let i = 0; i < candidates.length; i += 4) repos.push(...await Promise.all(candidates.slice(i, i + 4).map((p) => loadOne(p.repositoryId!, p.name, fetcher, token, now)))); const ready = repos.filter((repo) => repo.status === "ready").length; return { status: ready === repos.length ? "ready" : ready ? "partial" : "unavailable", fetchedAt: new Date(now).toISOString(), authenticated: Boolean(token), repos, message: ready === repos.length ? `${ready} repositories refreshed` : ready ? `${ready}/${repos.length} repositories available` : "GitHub metadata unavailable or rate-limited" };
}
