import type { PortfolioSnapshot, ProjectActivityEvent } from "./local-projects.ts";
import type { RemotePortfolioSource } from "./remote-portfolios.ts";
import type { HistorySample } from "./activity-history.ts";
import type { GitHubCollaboration } from "./github-collaboration.ts";
import { ownerForLocalRoot, type PortfolioOwner, type SharedProject, type SharedProjectSide } from "./shared-portfolio.ts";
export type ActivityFeedItem = { id: string; owner: PortfolioOwner; project: string; repositoryId: string | null; at: string; kind: ProjectActivityEvent["kind"]; head: string | null; detail: string };
export type MorningDeltaItem = { owner: PortfolioOwner; project: string; repositoryId: string | null; branch: string; morningHead: string | null; currentHead: string; commits: number; files: number; insertions: number; deletions: number; changed: boolean };
export type CollisionItem = { project: string; repositoryId: string | null; severity: "high" | "medium" | "low"; reason: string; eimyActive: boolean; johnyActive: boolean; drift: SharedProject["drift"] };
export type HandoffItem = { project: string; repositoryId: string | null; from: PortfolioOwner | "Both"; to: PortfolioOwner | "Both"; status: "coordinate" | "sync" | "wip" | "aligned"; action: string };
export type PersonaPulse = { owner: PortfolioOwner; repos: number; touched: number; commits: number; dirty: number; sharedTouched: number; files: number; insertions: number; deletions: number; lastActivity: string | null };
export type FreshnessItem = { owner: PortfolioOwner; source: "local" | "cache" | "missing"; generatedAt: string | null; ageMinutes: number | null; state: "fresh" | "aging" | "stale" | "missing"; device: string | null };
export type SyncItem = { project: string; repositoryId: string | null; eimy: { ahead: number | null; behind: number | null; fetchAgeMinutes: number | null; upstream: string | null } | null; johny: { ahead: number | null; behind: number | null; fetchAgeMinutes: number | null; upstream: string | null } | null; status: "in-sync" | "attention" | "unknown" };
export type ChangeVolumeItem = { owner: PortfolioOwner; project: string; repositoryId: string | null; files: number; insertions: number; deletions: number; commits: number };
export type HeatmapDay = { date: string; Eimy: number; Johny: number; eimyFiles: number; johnyFiles: number };
export type NexusInsights = { activityFeed: ActivityFeedItem[]; morningDelta: MorningDeltaItem[]; collisions: CollisionItem[]; handoffs: HandoffItem[]; pulse: PersonaPulse[]; freshness: FreshnessItem[]; sync: SyncItem[]; changeVolume: ChangeVolumeItem[]; heatmap: HeatmapDay[]; activityByHour: { hour: string; Eimy: number; Johny: number }[]; github: GitHubCollaboration };
function sides(project: SharedProject): [PortfolioOwner, SharedProjectSide][] { return [["Eimy", project.eimy], ["Johny", project.johny]].filter((entry): entry is [PortfolioOwner, SharedProjectSide] => Boolean(entry[1])); }
function isActive(side: SharedProjectSide | null) { return Boolean(side && (side.commitsToday > 0 || side.events.length > 0 || side.state === "Changes")); }
function eventDetail(event: ProjectActivityEvent) { if (event.kind === "branch-switch") return `${event.from ?? "?"} → ${event.to ?? "?"}`; if (event.kind === "working-tree") return `${event.count ?? 0} changed paths`; if (event.kind === "commit") return event.head ? `commit ${event.head}` : "commit observed"; return event.head ? `HEAD ${event.head}` : "HEAD changed"; }
function pulseFor(owner: PortfolioOwner, projects: SharedProject[]): PersonaPulse { const entries = projects.flatMap((p) => { const side = owner === "Eimy" ? p.eimy : p.johny; return side ? [{ project: p, side }] : []; }); const activities = entries.flatMap(({ side }) => side.events.map((e) => e.at)).filter(Boolean).sort(); return { owner, repos: entries.length, touched: entries.filter(({ side }) => isActive(side)).length, commits: entries.reduce((sum, { side }) => sum + side.commitsToday, 0), dirty: entries.filter(({ side }) => side.state === "Changes").length, sharedTouched: entries.filter(({ project, side }) => project.isShared && isActive(side)).length, files: entries.reduce((sum, { side }) => sum + side.changedFilesToday, 0), insertions: entries.reduce((sum, { side }) => sum + side.insertionsToday, 0), deletions: entries.reduce((sum, { side }) => sum + side.deletionsToday, 0), lastActivity: activities.at(-1) ?? entries.map(({ side }) => side.lastCommitAt).filter((x): x is string => Boolean(x)).sort().at(-1) ?? null }; }
function freshnessState(age: number | null): FreshnessItem["state"] { if (age === null) return "missing"; if (age <= 15) return "fresh"; if (age <= 60) return "aging"; return "stale"; }
export function buildNexusInsights(projects: SharedProject[], local: PortfolioSnapshot, remoteSources: RemotePortfolioSource[], history: HistorySample[], github: GitHubCollaboration, now = Date.now()): NexusInsights {
  const activityFeed: ActivityFeedItem[] = projects.flatMap((project) => sides(project).flatMap(([owner, side]) => side.events.map((event) => ({ id: `${owner}:${project.key}:${event.kind}:${event.at}:${event.head ?? ""}`, owner, project: project.name, repositoryId: project.repositoryId, at: event.at, kind: event.kind, head: event.head, detail: eventDetail(event) })))).sort((a, b) => Date.parse(b.at) - Date.parse(a.at)).slice(0, 60);
  const morningDelta: MorningDeltaItem[] = projects.flatMap((project) => sides(project).map(([owner, side]) => ({ owner, project: project.name, repositoryId: project.repositoryId, branch: side.branch, morningHead: side.dayStartHead, currentHead: side.head, commits: side.commitsToday, files: side.changedFilesToday, insertions: side.insertionsToday, deletions: side.deletionsToday, changed: Boolean(side.commitsToday || side.changedFilesToday || side.dayStartHead && side.dayStartHead !== side.head) }))).sort((a, b) => Number(b.changed) - Number(a.changed) || b.files - a.files).slice(0, 50);
  const collisions: CollisionItem[] = projects.filter((p) => p.isShared && (isActive(p.eimy) || isActive(p.johny)) && (p.drift !== "aligned" || isActive(p.eimy) && isActive(p.johny))).map((p) => { const eimyActive = isActive(p.eimy); const johnyActive = isActive(p.johny); const bothDirty = p.eimy?.state === "Changes" && p.johny?.state === "Changes"; const severity: CollisionItem["severity"] = bothDirty || p.drift === "head-and-working-tree" ? "high" : eimyActive && johnyActive && p.drift === "head-drift" ? "medium" : "low"; const reason = bothDirty ? "Both working trees have local changes" : eimyActive && johnyActive ? p.drift === "aligned" ? "Both active today, currently aligned" : "Both active today with repository drift" : p.drift === "working-tree" ? "One working tree has local changes" : "Shared repository needs comparison"; return { project: p.name, repositoryId: p.repositoryId, severity, reason, eimyActive, johnyActive, drift: p.drift }; }).sort((a, b) => ({ high: 3, medium: 2, low: 1 }[b.severity] - { high: 3, medium: 2, low: 1 }[a.severity])).slice(0, 12);
  const handoffs: HandoffItem[] = projects.filter((p) => p.isShared && (p.drift !== "aligned" || isActive(p.eimy) || isActive(p.johny))).map((p) => { const ea = isActive(p.eimy); const ja = isActive(p.johny); if (ea && ja && p.drift !== "aligned") return { project: p.name, repositoryId: p.repositoryId, from: "Both" as const, to: "Both" as const, status: "coordinate" as const, action: "Coordinate before sync; both personas changed this repository." }; if (p.eimy?.state === "Changes" && !ja) return { project: p.name, repositoryId: p.repositoryId, from: "Eimy" as const, to: "Johny" as const, status: "wip" as const, action: "Eimy has uncommitted work; treat as work in progress." }; if (p.johny?.state === "Changes" && !ea) return { project: p.name, repositoryId: p.repositoryId, from: "Johny" as const, to: "Eimy" as const, status: "wip" as const, action: "Johny has uncommitted work; treat as work in progress." }; if (ea && p.drift !== "aligned") return { project: p.name, repositoryId: p.repositoryId, from: "Eimy" as const, to: "Johny" as const, status: "sync" as const, action: "Eimy changed today; Johny should review/sync the shared repository." }; if (ja && p.drift !== "aligned") return { project: p.name, repositoryId: p.repositoryId, from: "Johny" as const, to: "Eimy" as const, status: "sync" as const, action: "Johny changed today; Eimy should review/sync the shared repository." }; return { project: p.name, repositoryId: p.repositoryId, from: "Both" as const, to: "Both" as const, status: "aligned" as const, action: "Shared repository is aligned." }; }).slice(0, 12);
  const localOwner = ownerForLocalRoot(local.root); const sources = new Map<PortfolioOwner, { generatedAt: string; device: string; source: "local" | "cache" }>(); sources.set(localOwner, { generatedAt: local.generatedAt, device: "This Mac", source: "local" }); for (const remote of remoteSources) if (remote.status === "ready" && remote.snapshot && remote.snapshot.owner !== localOwner) sources.set(remote.snapshot.owner as PortfolioOwner, { generatedAt: remote.snapshot.generatedAt, device: remote.snapshot.device, source: "cache" }); const freshness: FreshnessItem[] = (["Eimy", "Johny"] as PortfolioOwner[]).map((owner) => { const source = sources.get(owner); if (!source) return { owner, source: "missing", generatedAt: null, ageMinutes: null, state: "missing", device: null }; const ageMinutes = Math.max(0, Math.floor((now - Date.parse(source.generatedAt)) / 60000)); return { owner, source: source.source, generatedAt: source.generatedAt, ageMinutes, state: freshnessState(ageMinutes), device: source.device }; });
  const sync: SyncItem[] = projects.map((p) => { const value = (side: SharedProjectSide | null) => side ? { ahead: side.ahead, behind: side.behind, fetchAgeMinutes: side.fetchAgeMinutes, upstream: side.upstream } : null; const eimy = value(p.eimy), johny = value(p.johny); const known = [eimy, johny].filter(Boolean).some((x) => x!.ahead !== null || x!.behind !== null); const attention = [eimy, johny].filter(Boolean).some((x) => (x!.ahead ?? 0) > 0 || (x!.behind ?? 0) > 0); return { project: p.name, repositoryId: p.repositoryId, eimy, johny, status: known ? attention ? "attention" as const : "in-sync" as const : "unknown" as const }; }).filter((x) => x.eimy?.ahead !== null || x.eimy?.behind !== null || x.johny?.ahead !== null || x.johny?.behind !== null).sort((a, b) => Number(b.status === "attention") - Number(a.status === "attention")).slice(0, 20);
  const changeVolume: ChangeVolumeItem[] = projects.flatMap((p) => sides(p).map(([owner, side]) => ({ owner, project: p.name, repositoryId: p.repositoryId, files: side.changedFilesToday, insertions: side.insertionsToday, deletions: side.deletionsToday, commits: side.commitsToday }))).filter((x) => x.files || x.commits).sort((a, b) => b.files - a.files || b.commits - a.commits).slice(0, 20);
  const today = new Date(now); const dates = Array.from({ length: 7 }, (_, index) => { const d = new Date(today); d.setDate(today.getDate() - (6 - index)); const pad = (n: number) => String(n).padStart(2, "0"); return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`; }); const heatmap: HeatmapDay[] = dates.map((date) => { const value: HeatmapDay = { date, Eimy: 0, Johny: 0, eimyFiles: 0, johnyFiles: 0 }; for (const owner of ["Eimy", "Johny"] as PortfolioOwner[]) { const sample = history.filter((item) => item.owner === owner && item.localDate === date).sort((a, b) => Date.parse(b.generatedAt) - Date.parse(a.generatedAt))[0]; if (sample) { const commits = sample.projects.reduce((sum, p) => sum + p.commitsToday, 0); const files = sample.projects.reduce((sum, p) => sum + p.changedFilesToday, 0); if (owner === "Eimy") { value.Eimy = commits; value.eimyFiles = files; } else { value.Johny = commits; value.johnyFiles = files; } } } return value; });
  const activityByHour = Array.from({ length: 24 }, (_, hour) => ({ hour: `${String(hour).padStart(2, "0")}:00`, Eimy: 0, Johny: 0 })); for (const event of activityFeed) { const date = new Date(event.at); if (date.toDateString() !== new Date(now).toDateString()) continue; const row = activityByHour[date.getHours()]; row[event.owner] += 1; }
  return { activityFeed, morningDelta, collisions, handoffs, pulse: [pulseFor("Eimy", projects), pulseFor("Johny", projects)], freshness, sync, changeVolume, heatmap, activityByHour, github };
}
